## 排序
可参考 [Python Sorting](https://wiki.python.org/moin/HowTo/Sorting)

In [45]:
'''
基本排序 sort, reverse, sorted
'''
print ('Using list member method:')
a = [1, -1, 3, 5, 3, 9]
print('origin:', a)
print('sorted:', a) # 会在 a 上直接排序。
b = [1, -1, 3, 5, 3, 9]
print ('Use copy')
bsorted = b.copy()
bsorted.sort()
print ('orgin:', b)
print ('sorted:', bsorted)
breversed = b.copy()
breversed.reverse()
print ('reversed:', breversed)

print ('\nUsing sorted function:')
print (sorted(b))

Using list member method:
origin: [1, -1, 3, 5, 3, 9]
sorted: [1, -1, 3, 5, 3, 9]
Use copy
orgin: [1, -1, 3, 5, 3, 9]
sorted: [-1, 1, 3, 3, 5, 9]
reversed: [9, 3, 5, 3, -1, 1]

Using sorted function:
[-1, 1, 3, 3, 5, 9]


In [43]:
'''
获取排序下标 numpy.argsort
numpy.argsort(a, axis=-1, kind='quicksort', order=None)[source]

https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html

'''
import numpy as np
# 一维
a = [1, -3, 2, 0, 5]
sortedIndices = np.argsort(a)
print('origin a:', a)
print('sorted indices:', sortedIndices)
print('argsorted:', [a[i] for i in sortedIndices])

# 二维
print ('Two dimensions argsort:')
a = [[9, 3, 5], [-2, 5, -3]]
print ('Origin:\n', a[0], '\n', a[1])
print ('Order by row:') # 对每行进行排序。
sortedAxis1 = np.argsort(a)
print (np.argsort(a)) # 默认 axis = -1 , 即最后一个维度。 在这个例子中与 axis = -1, axis = 0 等价

m = len(a)
n = len(a[0])
for i in range(m):
    print ([a[i][sortedAxis1[i][j]] for j in range(n)])


print ('\nOrigin:\n', a[0], '\n', a[1])
print ('Order by col:') # 对每列进行排序。
sortedAxis0 = np.argsort(a, axis=0)
print (sortedAxis0)
for i in range(m):
    print([a[sortedAxis0[i][j]][j] for j in range(n)])


origin a: [1, -3, 2, 0, 5]
sorted indices: [1 3 0 2 4]
argsorted: [-3, 0, 1, 2, 5]
Two dimensions argsort:
Origin:
 [9, 3, 5] 
 [-2, 5, -3]
Order by row:
[[1 2 0]
 [2 0 1]]
[3, 5, 9]
[-3, -2, 5]

Origin:
 [9, 3, 5] 
 [-2, 5, -3]
Order by col:
[[1 0 1]
 [0 1 0]]
[-2, 3, -3]
[9, 5, 5]


In [70]:
'''
对字典进行排序, sorted, sorted(iterable, [key=None, reverse=False])
在 python3 中去掉了 cmp 参数。
因为 sorted 可以接受任务 iterable 的参数，所以也可以对字典排序，只要给出对 iterable items.
'''
import operator 
print ('Stirng sort:')
s = 'Hello FOO'
print (s, sorted(s))
print (s, sorted(s, key = str.lower))

print ('\nDict sort:')
d = {1: 'D', 2: 'B', 0: 'B', 4: 'E', 5: 'A'}
print (sorted(d))
print (sorted(d.items(), key=operator.itemgetter(1)))

print ('\nList sort:')
l = [('b',2),('a',4),('c',3),('d',4)]
# 根据下标 0 的值作为 key 来排序。
print (sorted(l, key = lambda x:x[0]))
# 根据下标 1 的值作为 key 来排序。
print (sorted(l, key = lambda x:x[1]))


Stirng sort:
Hello FOO [' ', 'F', 'H', 'O', 'O', 'e', 'l', 'l', 'o']
Hello FOO [' ', 'e', 'F', 'H', 'l', 'l', 'o', 'O', 'O']

Dict sort:
[0, 1, 2, 4, 5]
[(5, 'A'), (2, 'B'), (0, 'B'), (1, 'D'), (4, 'E')]

List sort:
[('a', 4), ('b', 2), ('c', 3), ('d', 4)]
[('b', 2), ('c', 3), ('a', 4), ('d', 4)]
