## Computing On Data

### Indexing

In [1]:
A = [1 2; 3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [2]:
A(3, 2)

ans =  6


In [3]:
A(2, :) % ':' semicolon means every element along with that row/column.

ans =

   3   4



In [4]:
A(:, 2)

ans =

   2
   4
   6



In [5]:
A(:, 2) = [10; 11; 12]

A =

    1   10
    3   11
    5   12



In [7]:
A = [A, [100; 101; 102]] % append a column to right A

A =

     1    10   100
     3    11   101
     5    12   102



In [8]:
size(A)

ans =

   3   3



In [10]:
A(:) % flatten, put all elements of A into a single vector.

ans =

     1
     3
     5
    10
    11
    12
   100
   101
   102



### Computing

In [12]:
A = [1 2; 3 4; 5 6]
B = [11 12; 13 14; 15 16]
C = [1 2; 2 1]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

   1   2
   2   1



In [14]:
A .* B % element-wise operations

ans =

   11   24
   39   56
   75   96



In [16]:
A * C % matrices multiplicaton

ans =

    5    4
   11   10
   17   16



In [18]:
A .^ 2 % element-wise squared.

ans =

    1    4
    9   16
   25   36



In [19]:
v = [1; 2; 3]

v =

   1
   2
   3



In [24]:
v ./ A % element to row operaton. vector 中一个每一个元素在矩阵上每一行上进行操作。

ans =

   1.00000   0.50000
   0.66667   0.50000
   0.60000   0.50000



In [25]:
v(1) ./ A
v(2) ./ A
v(3) ./ A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667

ans =

   2.00000   1.00000
   0.66667   0.50000
   0.40000   0.33333

ans =

   3.00000   1.50000
   1.00000   0.75000
   0.60000   0.50000



In [26]:
log(v)

ans =

   0.00000
   0.69315
   1.09861



In [27]:
log(A)

ans =

   0.00000   0.69315
   1.09861   1.38629
   1.60944   1.79176



In [28]:
exp(v), abs(v)

ans =

    2.7183
    7.3891
   20.0855

ans =

   1
   2
   3



In [29]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [30]:
A' % transpose

ans =

   1   3   5
   2   4   6



In [32]:
A''

ans =

   1   2
   3   4
   5   6



In [33]:
a = [1 15 2 0.5]

a =

    1.00000   15.00000    2.00000    0.50000



In [34]:
val = max(a)

val =  15


In [35]:
[val index] = max(a)

val =  15
index =  2


In [36]:
max(A)

ans =

   5   6



In [38]:
a < 3 % element-wise operation return a row vector.

ans =

   1   0   1   1



In [39]:
find(a <3)

ans =

   1   3   4



In [40]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [45]:
[r, c] = find(A >=7)
A(r(1), c(1))
A(r(2), c(2))
A(r(3), c(3))

r =

   1
   3
   2

c =

   1
   2
   3

ans =  8
ans =  9
ans =  7


In [46]:
a
sum(a)
prod(a)
floor(a)
ceil(a)

a =

    1.00000   15.00000    2.00000    0.50000

ans =  18.500
ans =  15
ans =

    1   15    2    0

ans =

    1   15    2    1



In [53]:
a = rand(3)
b = rand(3)

a =

   0.879481   0.881487   0.365635
   0.473730   0.158038   0.867293
   0.490340   0.094171   0.146699

b =

   0.660948   0.554974   0.578476
   0.626250   0.860917   0.080758
   0.220366   0.267954   0.224261



In [56]:
max(a, b) % 两个矩阵中的对应元素相比较，返回较大的放在新的矩阵中。

ans =

   0.87948   0.88149   0.57848
   0.62625   0.86092   0.86729
   0.49034   0.26795   0.22426



In [61]:
A
max(A, [], 1) % 1 dim column
max(A, [], 2) % 2 dim row

A =

   8   1   6
   3   5   7
   4   9   2

ans =

   8   9   7

ans =

   8   9   7

ans =

   8
   7
   9



In [64]:
max(A)
max(max(A))
max(A(:))

ans =

   8   9   7

ans =  9
ans =  9


In [65]:
A = magic(5)

A =

   17   24    1    8   15
   23    5    7   14   16
    4    6   13   20   22
   10   12   19   21    3
   11   18   25    2    9



In [67]:
sum(A, 1)
sum(A, 2)

ans =

   65   65   65   65   65

ans =

   65
   65
   65
   65
   65



In [68]:
I = eye(5)

I =

Diagonal Matrix

   1   0   0   0   0
   0   1   0   0   0
   0   0   1   0   0
   0   0   0   1   0
   0   0   0   0   1



In [72]:
A .* I
sum(A .* I)
sum(sum(A .* I))

ans =

   17    0    0    0    0
    0    5    0    0    0
    0    0   13    0    0
    0    0    0   21    0
    0    0    0    0    9

ans =

   17    5   13   21    9

ans =  65


In [75]:
flipud(I)
sum(A .* I)
sum(sum(A .* I))

ans =

Permutation Matrix

   0   0   0   0   1
   0   0   0   1   0
   0   0   1   0   0
   0   1   0   0   0
   1   0   0   0   0

ans =

   17    5   13   21    9

ans =  65


In [76]:
inv(A)
pinv(A) % pseudo-inverse of A

ans =

  -0.0049359   0.0511538  -0.0353846   0.0011538   0.0033974
   0.0431410  -0.0373077  -0.0046154   0.0126923   0.0014744
  -0.0302564   0.0030769   0.0030769   0.0030769   0.0364103
   0.0046795  -0.0065385   0.0107692   0.0434615  -0.0369872
   0.0027564   0.0050000   0.0415385  -0.0450000   0.0110897

ans =

  -0.0049359   0.0511538  -0.0353846   0.0011538   0.0033974
   0.0431410  -0.0373077  -0.0046154   0.0126923   0.0014744
  -0.0302564   0.0030769   0.0030769   0.0030769   0.0364103
   0.0046795  -0.0065385   0.0107692   0.0434615  -0.0369872
   0.0027564   0.0050000   0.0415385  -0.0450000   0.0110897

