## Fancy indexing and index tricks

相对于 Python 原生列表，NumPy 提供了许多索引方法。除了之前的整数索引与 : , 数组还可以用整数和布尔数组进行索引。

### Indexing with Array of Indices


In [2]:
import numpy as np

a = np.arange(12) ** 2
# 一维索引数组
i = np.array([ 1, 1, 1, 3, 8, 5])
print(a[i])

# 二维索引数组

j = np.array([[3, 4], [9, 7]])
print(a[j])

[ 1  1  1  9 64 25]
[[ 9 16]
 [81 49]]


当数组 a 是多维时，索引数组 i 中的元素的对应是 a 的第一个 axis.

例如：

In [3]:
palette = np.array([[0, 0, 0], 
                    [255, 0, 0],
                    [0, 255, 0],
                    [0, 0, 255],
                    [255, 255, 255]
                   ])
image = np.array([[0, 1, 2, 0], [0, 3, 4, 0]])
print(palette[image])

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]


当然我们可以用多个索引数组可索引一个数组的各个维度，这个多个索引数组的shape 应该是相同的， 或者可以被 broadcasting。

In [18]:
a = np.fromfunction(lambda i,j: i * 10 + j, (4, 4))
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])
print(i)
print(j)
print(a)
# i, j 的 shape 必须相同。
print(a[i,j])
print(a[j,i])

# 隐匿 Broadcasting
print('Broadcasting:')
print(a[i,2])
# 可以把 i,j 放到一个列表中，然后索引. 
l = [i, j]
print('List indexing:')
print(a[l])
# 但是我们却不能把它们放在一个 Array 中。 
# 放在数组中就不是我们想要的结果了。
print('Array of array indexing')
s = np.array([i, j])
print(s)
print(s.shape)
print(a[s])

[[0 1]
 [1 2]]
[[2 1]
 [3 3]]
[[  0.   1.   2.   3.]
 [ 10.  11.  12.  13.]
 [ 20.  21.  22.  23.]
 [ 30.  31.  32.  33.]]
[[  2.  11.]
 [ 13.  23.]]
[[ 20.  11.]
 [ 31.  32.]]
Broadcasting:
[[  2.  12.]
 [ 12.  22.]]
List indexing:
[[  2.  11.]
 [ 13.  23.]]
Array of array indexing
[[[0 1]
  [1 2]]

 [[2 1]
  [3 3]]]
(2, 2, 2)
[[[[  0.   1.   2.   3.]
   [ 10.  11.  12.  13.]]

  [[ 10.  11.  12.  13.]
   [ 20.  21.  22.  23.]]]


 [[[ 20.  21.  22.  23.]
   [ 10.  11.  12.  13.]]

  [[ 30.  31.  32.  33.]
   [ 30.  31.  32.  33.]]]]


另一种常用的索引是数组的最大值，最小值索引。

In [33]:
time = np.linspace(20, 145, 5)
data = np.sin(np.arange(20).reshape(5, 4))
print(time)
print(data)

colMaxIndices = data.argmax(axis = 0)
rowMaxIndices = data.argmax(axis = 1)
# 索引不是目的，目的是为了最大值。
print(colMaxIndices)
print(rowMaxIndices)

maxIndex = data.argmax() # 会把整个数组当成一个列表来索引。
print(maxIndex) 
print(data.flat[maxIndex])

[  20.     51.25   82.5   113.75  145.  ]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[2 3 0 2 3]
14
0.990607355695


In [35]:
'''
数组索引还可以用于赋值运算。
'''
a = np.arange(5)
# 如果一个索引出现了多次，则以最后一次为准。
a[[0, 0, 2]] = [1, 2, 3]
print(a)
# 注意自运算时出现多次，仅仅会计算一次。
a[[0, 0, 2]] += 1
print(a)

[2 1 3 3 4]
[3 1 4 3 4]


### Indexing with Boolean Arrays
我们可以用 Boolean 值的数组来索引数组。

In [47]:
a = np.fromfunction(lambda i,j: i*10 + j, (3, 4))
print('Basic:')
print(a)
b = a > 12
print(b)
print(a[b])

# 这个特性用在赋值上十分方便。
print('\nAssign:')
a[b] = -1
print(a)

# 多个一维 Boolean 数组来索引
print('\nMultiple Boolean arrays:')
a = np.fromfunction(lambda i,j: i*10 + j, (3, 4))
b1 = np.array([False, True, True])
b2 = np.array([True, False, True, False])
print(a[b1])
print( a[b1,:])
print(a[:,b2])

Basic:
[[  0.   1.   2.   3.]
 [ 10.  11.  12.  13.]
 [ 20.  21.  22.  23.]]
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]
[ 13.  20.  21.  22.  23.]

Assign:
[[  0.   1.   2.   3.]
 [ 10.  11.  12.  -1.]
 [ -1.  -1.  -1.  -1.]]

Multiple Boolean arrays:
[[ 10.  11.  12.  13.]
 [ 20.  21.  22.  23.]]
[[ 10.  11.  12.  13.]
 [ 20.  21.  22.  23.]]
[[  0.   2.]
 [ 10.  12.]
 [ 20.  22.]]


### The ix_() function
ix_() function 可以用来组合不同的向量得到对应的各自对应的多维数组。

In [54]:
data = np.sin(np.arange(20).reshape(5, 4))
print(data)
colMaxIndices = data.argmax(axis = 0)
rowMaxIndices = data.argmax(axis = 1)
print('col Max:', colMaxIndices, colMaxIndices.shape)
print('row Max:', rowMaxIndices, rowMaxIndices.shape)
ix, jx = np.ix_(colMaxIndices, rowMaxIndices)
print(ix, ix.shape)
print(jx, jx.shape)
print(ix + jx)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
col Max: [2 0 3 1] (4,)
row Max: [2 3 0 2 3] (5,)
[[2]
 [0]
 [3]
 [1]] (4, 1)
[[2 3 0 2 3]] (1, 5)
[[4 5 2 4 5]
 [2 3 0 2 3]
 [5 6 3 5 6]
 [3 4 1 3 4]]
