## Linear Algebra
### Simple Array Operations
See [linalg.py](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html) in numpy folder for more.


In [10]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print('Original Array:\n', a)
print('a Transpose:\n', a.transpose())
print('a Inverse:\n', np.linalg.inv(a))

# 单位矩阵
u = np.eye(2)
print('Unit Matrix:\n', u)
print('Matrix product:\n', np.dot(a, u))
print('Matrix trace:\n', np.trace(u))

Original Array:
 [[ 1.  2.]
 [ 3.  4.]]
a Transpose:
 [[ 1.  3.]
 [ 2.  4.]]
a Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Unit Matrix:
 [[ 1.  0.]
 [ 0.  1.]]
Matrix product:
 [[ 1.  2.]
 [ 3.  4.]]
Matrix trace:
 2.0
