## Eager Execution basics

该文本介绍四个方面的内容，包括：

- 导入必要的包
- 创建和使用 Tensors
- 使用 GPU 加速
- Datasets

In [4]:
import tensorflow as tf

print(tf.__version__)
# tf.enable_eager_execution() , tf 2.0 是默认开启 eagar execution 。

2.0.0-alpha0


### Tensors, 张量

TF 中一个 Tensor 就是一个多维数组。和 NumPY 中的 `ndarray` 对象类似，张量也有一个 data type 和 shape 属性。另外，张量可以寄生在加速器的内存(accelerator memory) 中 （如: GPU)。

TF 提供丰富的 API 来创建和使用 Tensors, 如: (`tf.add, tf.matmul, tf.linalg.inv etc.`) . 这些操作可以自动将 Pyhton 类型转换成 Tensors.

In [6]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

# operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [8]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


TF 中的 Tensors 与 NumPy arrays 的两个最主要的不同是：

1. 张量可以使用加速器加速，如 GPU, TPU.
2. 张量是不可改变的(immutable)。


### NumPy 兼容

TF Tensors 与 Numpy ndarrays 之间的转换非常简单。

- TF 的操作自动将 NumPy ndarrays 转换成 Tensors.
- NumPy 的操作自动将 Tensors 转换成 ndarrays

Tensors 可以显示调用 `.numpy()` 来转换成 ndarrays。但是如果 Tensors 是寄宿在 GPU 上的话，那么转换成本会高一些，转换过各需要将 Tensors 拷贝到主机内存上。

In [11]:
import numpy as np

ndarray = np.ones([3, 3])

tensor = tf.multiply(ndarray, 42)
print(tensor)

print(np.add(tensor, 1))
print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


### GPU 加速

许多 TF 的操作都可以使用 GPU 来完成运算。不用合适任何标注，TF 自动决定是否使用 GPU (必要时可能会在 GPU 和 CPU 中来回拷贝 Tensors).


In [16]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available")
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available
False
Is the Tensor on GPU #0:  
False
