## Basics
Numpy 中的主要对象是同类型的多维数组（the homogeneous multidimensional array）。 In NumPy dimensions are called **axes**. The number of axes is **rank（秩）**.

### Axes 与 Rank

**维度：**称为 Axes, 维度是 axis 的个数, 用整数却索引它。
如 array([[1, 2, 3], [2, 3, 4]])
axis 0 表示第一维，即列。第一维有两个元素。
axis 1 表示第二维, 即行。第二维有三个元素。

**秩：** 数组中维的个数称为 Rank.


## Basic Operation

In [2]:
import numpy as np

In [3]:
'''
在数组上进行的数学运算都是按对应元素来操作的（elementwise）。 
返回的也是一个同样维度的数组。
'''
a = np.linspace(10, 50, 5)
print(a)
b = np.arange(5)
print(b)
print('a-b: \t', a -b )
print('b ** 2:\t', b**2)
print('10*np.sin(a):\t', 10 * np.sin(a))
print('a<35:\t', a < 34)


[10. 20. 30. 40. 50.]
[0 1 2 3 4]
a-b: 	 [10. 19. 28. 37. 46.]
b ** 2:	 [ 0  1  4  9 16]
10*np.sin(a):	 [-5.44021111  9.12945251 -9.88031624  7.4511316  -2.62374854]
a<35:	 [ True  True  True False False]


In [4]:
'''
在 numpy 中 * 的数组运算也是 elementwise 运算。 
要想实现矩阵的相乘可以 dot function。
'''
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A)
print(B)
# elementwise product
print('A * B:\n', A * B)
# matrix product
print('A.dot(B):\n', A.dot(B))
# another matrix product
print('np.dot(A, B):\n', np.dot(A, B))


[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
A * B:
 [[2 0]
 [0 4]]
A.dot(B):
 [[5 4]
 [3 4]]
np.dot(A, B):
 [[5 4]
 [3 4]]


In [5]:
'''
而对于一些自运算，如 +=, *= 是直接在当前数组上操作，而不是新建一个。
一般可以用 np.ones, np.zeros, np.random.random, np.arange().reshape() 
来创建 narray
'''
# 默认是 float
a = np.ones((2, 3))
print(a)

# 可以指定类型
a = np.ones((2, 3), dtype=int)
print(a)

a = np.ones(a.shape)
print(a)

b = np.random.random((2, 3))
print(a)
print(b)
print()
print('a *= 3:\n', a * 3)
b += a
print('b += a:\n', b)

c = a + b 
print('c = a + b :\n', c)

# 从 float64 到 int64 转换会报错， upcasting。
a += b


[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.79894068 0.42224762 0.75984331]
 [0.08518691 0.15802567 0.93234703]]

a *= 3:
 [[3. 3. 3.]
 [3. 3. 3.]]
b += a:
 [[1.79894068 1.42224762 1.75984331]
 [1.08518691 1.15802567 1.93234703]]
c = a + b :
 [[2.79894068 2.42224762 2.75984331]
 [2.08518691 2.15802567 2.93234703]]


In [6]:
'''
许多一元操作，如元素的 sum 都被实现成了成员方法。
'''
a = np.random.random((2, 3))
print(a)
print('a.sum:', a.sum())
print('a.min:', a.min())
print('a.max:', a.max())
print()
'''
这些一元操作默认是把数组中的所有元素看成一个列表来操作的，并不管数组的维度。
通过指定 axis 参数可指定 axis 值来在对应的索引维度上操作。
'''
print('With axis parameter')
b = np.arange(12).reshape(3,4)
print(b)
print('b.sum(axis = 0):', b.sum(axis = 0)) # each column
print('b.sum(axis = 1):', b.sum(axis = 1)) # each row
print('b.sum():', b.sum())
print('b.min(axis = 0):', b.min(axis = 0))
# cumulative sum , 计算累积和。
print('b.cumsum():\n')
print(b.cumsum())
print('b.cumsum(axis = 1):\n', b.cumsum(axis = 1))
print('b.cumsum(axis = 0):\n', b.cumsum(axis = 0))

[[0.73861637 0.25565898 0.06344466]
 [0.83554523 0.66227144 0.24725539]]
a.sum: 2.8027920667763837
a.min: 0.06344466168847385
a.max: 0.8355452289079873

With axis parameter
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b.sum(axis = 0): [12 15 18 21]
b.sum(axis = 1): [ 6 22 38]
b.sum(): 66
b.min(axis = 0): [0 1 2 3]
b.cumsum():

[ 0  1  3  6 10 15 21 28 36 45 55 66]
b.cumsum(axis = 1):
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
b.cumsum(axis = 0):
 [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [7]:
'''
Univeral Functions:
Numpy 提供了一些数学函数，如：sin, cos, exp. 这些函数都是 elementwise 操作，
返回一个数组。这些函数被称为 Universal Functions (ufunc)。
'''
B = np.arange(6).reshape(2, 3)
print(B)
print('np.exp(B):\n', np.exp(B))
print('np.sqrt(B):\n', np.sqrt(B))
C = np.linspace(0, 3 * np.pi, 6).reshape(2, 3)
print('np.add(B, C):\n', np.add(B, C))

[[0 1 2]
 [3 4 5]]
np.exp(B):
 [[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]
np.sqrt(B):
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
np.add(B, C):
 [[ 0.          2.88495559  5.76991118]
 [ 8.65486678 11.53982237 14.42477796]]


### Indexing, Slicing and Iterating

In [8]:
'''
一维数组可以像 Python 中的 list 一样进行  indexed, sliced, iterated.
'''
a = np.arange(10) ** 3
print(a)
print(a[2])
print(a[2:5])
# 进行了一次 slice 后，还可以再进行次 slice。
print()
print(a[:6])
print(a[:6:2])
print(a[:6:3])
# reverse a
print()
print(a[:])
print(a[::])
print(a[::-1])

'''
对于多维数组，第一个 axis 都可以有一个 index, indices 用逗号分隔。
'''
print('\n\nMultiple array:')
def f(i, j):
    return 10 * i + j

b = np.fromfunction(f, (5, 4), dtype = int)
print(b)
print(b[2,3])
print(b[0:5, 1]) # each row in the second column of  b
print(b[:, 1]) # equivalent to the previous example
print(b[1:3,2:4])

# 如果少传一个 index ，则被认为是 :
print(b[-1])
print(b[-1,:]) # 与 b[-1] 等价。

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]

[  0   1   8  27  64 125]
[ 0  8 64]
[ 0 27]

[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]


Multiple array:
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[12 13]
 [22 23]]
[40 41 42 43]
[40 41 42 43]


In [9]:
'''
在多维数组中，b[i]被认为其它维度都是由 : 来替代。 Numpy 也允许你用 ...
来表示。
... 表示需要用多个 : 来完成一个完整的索引。
如: 对一个秩为5，即5维数组。
    x[1, 2, ...] <=> x[1, 2, :, :, :]
    x[..., 3] <=> x[:, :, :, :, 3]
    x[4, ..., 5, :] <=> x[4, :, :, 5, :]
'''
def f(i, j, k):
    return 100 * i + 10 * j + k

c = np.fromfunction(f, (2, 2, 3), dtype=int)
print(c)
print(c.shape)
print(c[1, ...])
print(c[..., 2])

[[[  0   1   2]
  [ 10  11  12]]

 [[100 101 102]
  [110 111 112]]]
(2, 2, 3)
[[100 101 102]
 [110 111 112]]
[[  2  12]
 [102 112]]


In [10]:
'''
Iterating 一个多维数组时，可分别对各个 axis 进行索引。
但是如果想对所数组中的所有元素进行遍历，可以使用 flat 属性。
'''
a = np.arange(6).reshape(3, 2)
for row in a:
    for ele in row:
        print (ele)
print ('Using flat attribute')
for ele in a.flat:
    print(ele)

0
1
2
3
4
5
Using flat attribute
0
1
2
3
4
5


## Shape Manipulation
### Changing the Shape of an Array


In [11]:
'''
下面的三个操作 reval, reshape, T 不会在原数组上操作，而仅仅是返回一个新的改变后的数组。
但是与 reshape 不同是， resize 会在数组本身上进行操作。
'''
a = np.floor(10 * np.random.random((3, 4)))
print(a)
print(a.shape)
print('a.ravel():\n', a.ravel())
print('a.reshape(6,2):\n', a.reshape(6, 2))
print('a.T:\n', a.T)

print('\nresize :')
a.resize(6,2)
print(a)

[[3. 3. 7. 0.]
 [9. 9. 7. 7.]
 [9. 8. 5. 7.]]
(3, 4)
a.ravel():
 [3. 3. 7. 0. 9. 9. 7. 7. 9. 8. 5. 7.]
a.reshape(6,2):
 [[3. 3.]
 [7. 0.]
 [9. 9.]
 [7. 7.]
 [9. 8.]
 [5. 7.]]
a.T:
 [[3. 9. 9.]
 [3. 9. 8.]
 [7. 7. 5.]
 [0. 7. 7.]]

resize :
[[3. 3.]
 [7. 0.]
 [9. 9.]
 [7. 7.]
 [9. 8.]
 [5. 7.]]


### Stacking together different arrays
可以在不同的维度上对数组进行拼接。

In [125]:
'''
Several arrays can be stacked together along different axes:
'''
a = np.floor(10 * np.random.random((2, 2)))
b = np.ceil(10 * np.random.random((2, 2)))
print (a)
print (b)
# 垂直连接
print('np.vstack((a, b))')
print(np.vstack((a,b)))
print('np.hstack((a, b))')
print(np.hstack((a, b)))

'''
一维数组可以使用 newaxis 来转成新的维度的数组。
'''
c = np.array([4, 2])
d = np.array([1, 5])
print (c)
print ('c[:, np.newaxis]:\n', c[:, np.newaxis])
print('c[:, np.newaxis, np.newaxis]:\n',c[:, np.newaxis, np.newaxis])

# 将一维数组使用 newaxis 来进行二维数组的连接。
print('\nh v:')
h = np.hstack((c[:, np.newaxis], d[:, np.newaxis]))
v = np.vstack((c[:, np.newaxis], d[:, np.newaxis]))
print(h)
print(v)

[[ 4.  3.]
 [ 4.  0.]]
[[  2.  10.]
 [ 10.   1.]]
np.vstack((a, b))
[[  4.   3.]
 [  4.   0.]
 [  2.  10.]
 [ 10.   1.]]
np.hstack((a, b))
[[  4.   3.   2.  10.]
 [  4.   0.  10.   1.]]
[4 2]
c[:, np.newaxis]:
 [[4]
 [2]]
c[:, np.newaxis, np.newaxis]:
 [[[4]]

 [[2]]]

h v:
[[4 1]
 [2 5]]
[[4]
 [2]
 [1]
 [5]]


### Splitting one array into several small ones
使用 vsplit, hsplit 可以对数组进行分隔。


In [130]:
a = np.floor(10 * np.random.random((2, 12)))
print(a)
# 水平分隔成三个数组。
print('\nnp.hsplit(a, 3):')
print(np.hsplit(a, 3))

print('\nnp.hsplit(a, (3,4)):')
print(np.hsplit(a, (3, 4)))

[[ 0.  6.  9.  6.  3.  6.  3.  3.  3.  6.  1.  1.]
 [ 5.  6.  4.  2.  4.  3.  5.  1.  6.  0.  8.  2.]]

np.hsplit(a, 3):
[array([[ 0.,  6.,  9.,  6.],
       [ 5.,  6.,  4.,  2.]]), array([[ 3.,  6.,  3.,  3.],
       [ 4.,  3.,  5.,  1.]]), array([[ 3.,  6.,  1.,  1.],
       [ 6.,  0.,  8.,  2.]])]

np.hsplit(a, (3,4)):
[array([[ 0.,  6.,  9.],
       [ 5.,  6.,  4.]]), array([[ 6.],
       [ 2.]]), array([[ 3.,  6.,  3.,  3.,  3.,  6.,  1.,  1.],
       [ 4.,  3.,  5.,  1.,  6.,  0.,  8.,  2.]])]


## Copies
### 非 Copy 操作

In [12]:
a = np.arange(12)
b = a
print( b is a )
'''
python 函数在传递对象时，也是根据引用来传递的而不是一个copy.
'''
def f(x):
    print('id(x):', id(x))
print ('id(a):', id(a))
f(a)

True
id(a): 4642799248
id(x): 4642799248


In [13]:
'''
view 视图操作。
'''
a = np.arange(12)
c = a.view()
print('c is a:', c is a)
print(c)
print ('c.base is a', c.base is a)
print ('c.flags.owndata', c.flags.owndata)
# 视图的值改变会影响。因为其实还是因为视图不 owndata.
c.shape = 2, 6
print(c.shape, a.shape)
c[0] = 12
print(c)
print(a)

c is a: False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
c.base is a True
c.flags.owndata False
(2, 6) (12,)
[[12 12 12 12 12 12]
 [ 6  7  8  9 10 11]]
[12 12 12 12 12 12  6  7  8  9 10 11]


### Deep copy
Copy 方法会对数据进行一个完全的 copy.


In [150]:
a = np.arange(12).reshape(3, 4)
b = a.copy()
print('b is a:', b is a)
b[0,0] = 12
print (b)
print (a)

b is a: False
[[12  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
