## Broadcasting 散布，扩散，广播，撒播
Broadcasting 广播描述的是 Numpy 在进行数组运算时怎样处理不同维度的数组的，则于某些限制，维度低的数组将会被 “扩散（Broadcasting）”成现高维度同维的数组。

In [1]:
import numpy as np
'''
一个最常用的扩散 case。用在数组的 elementwise 运算上。
'''
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
# times 2 elementwise
print('a * b:', a * b)
# equivalent to the previous example.
s = 2
print('a * s:', a * s)

a * b: [2. 4. 6.]
a * s: [2. 4. 6.]


我们可以认为标量(scalar) s 在运算进被扩散成了一个与 a 同 shape 的数组。新数组中元素都是原始标量的拷贝。**扩散:**仅仅只是概念上，Numpy 在实现上足够智能，并不会去真正的 copy 去扩散, 而是在实现这些操作时尽可能的在空间和时间效率上节省。

第二个例子效率更高，因为在计算进扩散占用更少的内存空间(扩散只一个概念), s 是一相标量而不是一个数组。

### General Broadcasting Rule 扩散规则

在完成两个数组的操作时，NumPy 会比较两个数组的 shape,**扩散规则** 是维度要兼容下面两种情况之一才能完成运算：

1. 对应维度相等 ， 或
2. 对应维度其中一个等于1

如果两个条件都不满足，则会报 **ValueError: frames are not aligned ** 异常。

例如下面的运算都是满足扩散规则的：

Ex1.

```
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3
```

EX2.

```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```


In [2]:
'''
Ex1.
Image  (3d array): 2 x 2 x 3
Scale  (1d array):         3
Result (3d array): 2 x 2 x 3
'''
a = np.arange(12).reshape(2, 2, 3)
b = np.array([1, -1, -1])
print (a.shape, b.shape)
print (a * b)

(2, 2, 3) (3,)
[[[  0  -1  -2]
  [  3  -4  -5]]

 [[  6  -7  -8]
  [  9 -10 -11]]]


In [3]:
'''
Ex2. 对应维度上有一个是等于 1 的。

'''
a = np.arange(8).reshape(2, 1, 4, 1)
b = np.arange(15).reshape(3,1,5)
print(a)
print(b)
print('a.shape:', a.shape)
print('b.shape:   ', b.shape)
c = a *  b
print ('a * b shape:', c.shape)
print(a * b)

[[[[0]
   [1]
   [2]
   [3]]]


 [[[4]
   [5]
   [6]
   [7]]]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]
a.shape: (2, 1, 4, 1)
b.shape:    (3, 1, 5)
a * b shape: (2, 3, 4, 5)
[[[[ 0  0  0  0  0]
   [ 0  1  2  3  4]
   [ 0  2  4  6  8]
   [ 0  3  6  9 12]]

  [[ 0  0  0  0  0]
   [ 5  6  7  8  9]
   [10 12 14 16 18]
   [15 18 21 24 27]]

  [[ 0  0  0  0  0]
   [10 11 12 13 14]
   [20 22 24 26 28]
   [30 33 36 39 42]]]


 [[[ 0  4  8 12 16]
   [ 0  5 10 15 20]
   [ 0  6 12 18 24]
   [ 0  7 14 21 28]]

  [[20 24 28 32 36]
   [25 30 35 40 45]
   [30 36 42 48 54]
   [35 42 49 56 63]]

  [[40 44 48 52 56]
   [50 55 60 65 70]
   [60 66 72 78 84]
   [70 77 84 91 98]]]]


- 下面是一些合法扩散的例子:

扩散合法，对应维度的值满足: 1) 维度值缺失；2) 维度值为 1; 3）维度值完全相等。

```
# 右对齐：B 的第二个维度值缺失，第一维度值为 1
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

# 右对齐：B 的第二个维度值缺失，第一维度值相等
A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

# 右对齐：B 的第二个维度值1，其余相等
A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

# 右对齐：B 的第一个维度值1，第二个维度值相等，第三个维度值缺失
A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

- 下面是不满足扩散的例子:

```
# 维度不相等
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

# 第一个维度为 1， 但是第二个维度却不为相等也不为1.
A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

扩散提供了一个对数组进行外部操作的快捷的方法。下面一个例子是相加的例子。

In [4]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print((a[:, np.newaxis]).shape, b.shape)
print(a[:, np.newaxis] + b) # a a[:, np.newaxis] make 4x1.


(4, 1) (3,)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [8]:
# 对于 (3,) 的对象会应用怎样的规则那？

a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
m = np.array([-1, 0, 1])

print('m.shape:', m.shape)
# b : 4 x 3
# m :     3
print('b * m', b * m)
print('m * b', m * b)

m.shape: (3,)
b * m [[ 0  0  2]
 [-3  0  5]
 [-6  0  8]
 [-9  0 11]]
m * b [[ 0  0  2]
 [-3  0  5]
 [-6  0  8]
 [-9  0 11]]


In [9]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
m = np.array([-1, 0, 1])

print('m.shape:', m.shape)
# 下面的 broadcasting 的规则将失效
# a : 3 x 4
# m :     3
print('a * m', a * m)
print('m * a', m * a)

m.shape: (3,)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

参考: 
-  [Numpy 中的扩散](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)
- [Broadcasting](https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html)
    