## Linear Algebra
### Simple Array Operations
See [linalg.py](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html) in numpy folder for more.


In [4]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print('Original Array:\n', a)
print('a Transpose (a.transpose()):\n', a.transpose())
print('a Transpose (a.T):\n', a.T)

print('a Inverse:\n', np.linalg.inv(a))

# 特征值和特征向量

eig_vals, eig_vecs = np.linalg.eig(a)

print('a eigenvalues:', eig_vals)
print('a eigenvecs:\n', eig_vecs)

# svd

# 单位矩阵
u = np.eye(2)
print('Unit Matrix:\n', u)
print('Matrix product:\n', np.dot(a, u))
print('Matrix trace:\n', np.trace(u))

Original Array:
 [[1. 2.]
 [3. 4.]]
a Transpose (a.transpose()):
 [[1. 3.]
 [2. 4.]]
a Transpose (a.T):
 [[1. 3.]
 [2. 4.]]
a Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
a eigenvalues: [-0.37228132  5.37228132]
a eigenvecs:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Unit Matrix:
 [[1. 0.]
 [0. 1.]]
Matrix product:
 [[1. 2.]
 [3. 4.]]
Matrix trace:
 2.0
