## Gradients 

在自定义操作的时候，如何验证自己实现定义的操作是否正确那？那就先用系统的实现来验证一遍。

### 权重矩阵的梯度求法

In [2]:
import tensorflow as tf
import numpy as np


In [3]:
x = np.array([1, 2, -1]).reshape(3, 1)
weights = np.arange(1, 10).reshape(3, 3)
print(x)
print(weights)

[[ 1]
 [ 2]
 [-1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(weights.dot(x))

[[ 2]
 [ 8]
 [14]]


In [8]:
x = tf.Variable(x, name="inputs", dtype="double")
W = tf.Variable(weights, name="weights", dtype="double")

In [9]:
def run():
    with tf.GradientTape() as t:
        z = tf.matmul(W, x)
    gradients = t.gradient(z, [W, x])
    print('dz_dw = ', gradients[0])
    print('dz_dx = ', gradients[1])
    

In [10]:
run()

dz_dw =  tf.Tensor(
[[ 1.  2. -1.]
 [ 1.  2. -1.]
 [ 1.  2. -1.]], shape=(3, 3), dtype=float64)
dz_dx =  tf.Tensor(
[[12.]
 [15.]
 [18.]], shape=(3, 1), dtype=float64)
