In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Parameters
learning_rate = 0.01
training_steps = 1000
display_step = 50

In [14]:
# Training Data
X = np.random.randn(10, 2)
       
y = np.random.randn(10, 1)

n_samples = 10

In [21]:
# Weight and Bias, initialized randomly
W = tf.Variable(np.random.randn(2, 1), name="weight")
b = tf.Variable(np.random.randn(), name="bias")

# Linear_regression (Wx + b)
def linear_regression(x):
    return tf.matmul(x, W)

# Mean square error.
def mean_square(y_pred, y_true):
    return tf.reduce_sum(tf.pow(y_pred - y_true, 2) / (2 * n_samples))

# Stochastic Gradient Descent Optimizer
optimizer = tf.optimizers.SGD(learning_rate)

In [31]:
# Optimize processes
def run_optimization():
    # Wrap computation inside a GradientTape for audo diff
    with tf.GradientTape() as g:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)
    
    # compute gradients
    gradients = g.gradient(loss, [W])
    print('gradients:', gradients)
    optimizer.apply_gradients(zip(gradients, [W]))

In [32]:

# Run training for the given number of steps.
for step in range(1, training_steps + 1):
    # Run the optimization to update W and b values.
    run_optimization()
    
    if step % display_step == 0:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)
        print("step: %i, loss: %f" % (step, loss))

gradients: [<tf.Tensor: id=158304, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158372, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158440, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158508, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158576, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158644, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158712, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=158780, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=163892, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=163960, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=164028, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=164096, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=164164, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=164232, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=164300, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=164368, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=174332, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174400, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174468, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174536, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174604, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174672, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174740, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=174808, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=180476, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180544, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180612, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180680, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180748, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180816, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180884, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=180952, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=185520, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
step: 400, loss: 32.275462
gradients: [<tf.Tensor: id=185600, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=185668, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=185736, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=185804, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=185872, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=185940, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=186008, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5

gradients: [<tf.Tensor: id=190984, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191052, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191120, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191188, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191256, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191324, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191392, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=191460, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=196652, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=196720, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=196788, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=196856, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=196924, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=196992, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=197060, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=197128, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=205788, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=205856, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=205924, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=205992, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
step: 700, loss: 32.275462
gradients: [<tf.Tensor: id=206072, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=206140, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=206208, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=206276, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5

gradients: [<tf.Tensor: id=215072, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215140, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215208, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215276, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215344, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215412, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215480, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=215548, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient

gradients: [<tf.Tensor: id=221148, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221216, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221284, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221352, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221420, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221488, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221556, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradients: [<tf.Tensor: id=221624, shape=(2, 1), dtype=float64, numpy=
array([[2.18713936e-14],
       [5.55111512e-15]])>]
gradient