## 自定义 Layer 

我们可以通过继承 `tf.keras.Layer` 类来实现的自定义层。当然我们需要实现下面三个方法：

- `__init__`: 初始化
- `build`: 本层的参数初始化, 用于创建 variables 参数。当然我们也可以在 `__init__` 中创建，但是在 build 中创建可延迟创建。
- `call`: 在 call 中实现前向计算。

下面的例子，我们在 call 方法中调用了 `tf.matmul` 来实现 FP。

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
class MyDenseLayer(keras.layers.Layer):
    
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape):
        self.kernel = self.add_variable(
            'kernel', 
            shape=[int(input_shape[-1]), self.num_outputs]
        )
        
    def call(self, input):
        return tf.matmul(input, self.kernel)

In [6]:
layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


In [8]:
print(layer.trainable_variables)

[<tf.Variable 'my_dense_layer_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.27690303,  0.50965995, -0.20736629,  0.11878991,  0.5912917 ,
        -0.28969958, -0.24481192,  0.01447201, -0.16940105,  0.01887351],
       [-0.12437528,  0.1136288 ,  0.5395861 ,  0.40884382, -0.58653873,
        -0.45170894, -0.47930998, -0.6269844 ,  0.57022804,  0.3909331 ],
       [-0.3814115 ,  0.49193782,  0.35832113,  0.40289456, -0.15691134,
         0.5845035 ,  0.46006674,  0.44904023,  0.38020808, -0.4454969 ],
       [-0.08192688, -0.534907  , -0.53095317,  0.5481878 , -0.5520864 ,
        -0.06580305, -0.18820325,  0.50080425, -0.1010533 , -0.14325225],
       [-0.04376864, -0.41920182,  0.5421857 ,  0.11240715,  0.30562395,
        -0.09442234,  0.4621666 , -0.21266186,  0.09309238, -0.29268822]],
      dtype=float32)>]


In [14]:
layer.kernel

<tf.Variable 'my_dense_layer_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.27690303,  0.50965995, -0.20736629,  0.11878991,  0.5912917 ,
        -0.28969958, -0.24481192,  0.01447201, -0.16940105,  0.01887351],
       [-0.12437528,  0.1136288 ,  0.5395861 ,  0.40884382, -0.58653873,
        -0.45170894, -0.47930998, -0.6269844 ,  0.57022804,  0.3909331 ],
       [-0.3814115 ,  0.49193782,  0.35832113,  0.40289456, -0.15691134,
         0.5845035 ,  0.46006674,  0.44904023,  0.38020808, -0.4454969 ],
       [-0.08192688, -0.534907  , -0.53095317,  0.5481878 , -0.5520864 ,
        -0.06580305, -0.18820325,  0.50080425, -0.1010533 , -0.14325225],
       [-0.04376864, -0.41920182,  0.5421857 ,  0.11240715,  0.30562395,
        -0.09442234,  0.4621666 , -0.21266186,  0.09309238, -0.29268822]],
      dtype=float32)>

上面我们只在 call 方法调用了 `tf.matmul` 中实现了前向方法，而 BP 怎么实现那？而且我们也没有实现 `bias`。